[package]
name = "smart_trapper_b1"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
image = "0.24"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
clap = { version = "4", features = ["derive"] }
